language: C++

dist: xenial

compiler:
        -gcc

before_script:
  - set -e
  - mkdir sfml_install
  # TODO: Maybe investigate why the certificate checks for the SFML sources fail
  - wget http://www.sfml-dev.org/files/SFML-2.5.1-sources.zip --no-check-certificate
  - unzip -q SFML-2.5.1-sources.zip
  - pushd SFML-2.5.1 && mkdir build && cd build && cmake .. && make
  - make DESTDIR=/home/travis/build/jeremyletang/rust-sfml/sfml_install install
  - popd
  - wget http://www.sfml-dev.org/files/CSFML-2.5-sources.zip --no-check-certificate
  - unzip -q CSFML-2.5-sources.zip
  - pushd CSFML-2.5
  - mkdir build && cd build && cmake -DSFML_DIR='/home/travis/build/jeremyletang/rust-sfml/sfml_install/usr/local/lib/cmake/SFML/' .. && make
  - make DESTDIR=/home/travis/build/jeremyletang/rust-sfml/sfml_install install
  - popd
  - mkdir .cargo
  - mv .travis.cargo.config .cargo/config
  - cargo build --verbose
  - cargo test --verbose -- --skip font --skip audio --skip window --skip graphics
  - cargo doc --verbose

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code && make 
