language: C++

dist: xenial

os: linux
  compiler: clang
  addons:
    apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-8.3.0', 'kalakris-cmake']
      packages: ['clang-8.3.0', 'cmake']
  env: COMPILER=clang++-8.3.0

before_script:
  
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.gz
  - tar -xvf /tmp/sfml.tar.gz
  - sudo cp -r SFML-2.5.1/* /usr/
  - wget http://www.bromeon.ch/libraries/thor/download/v2.0/thor-v2.0-linux64-make.tar.gz -O /tmp/thor.tar.gz
  - tar -xvf /tmp/thor.tar.gz
  - sudo cp -r thor-v2.0-linux64-make/* /usr/
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 libxcb-image0 libxcb-randr0 libudev1
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  
  
  
script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code && make all 
